name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    # local repo
     uses: ./.github/workflows/main.yml
    # other repo
    #uses: octo-org/example-repo/.github/workflows/called-workflow.yml@v1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
       - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
       - run: npm ci
       - run: npm run build --if-present
       - name: Run test
         run: npm run qa2
